# Generated by Django 2.2.12 on 2020-06-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_recipe', to='book.RecipeItem'),
        ),
    ]
